default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=500', '--enforce-all']
        exclude: |
            (?x)^(
                notebooks/action_analysis.ipynb|
                notebooks/coil_correlation.ipynb|
                notebooks/seasonality_analysis.ipynb|
                notebooks/coil_data_analysis_0607.ipynb|
                notebooks/mpc_cartpole_tutorial.ipynb|
                notebooks/dynamics_train_mide_tutorial.ipynb|
            )$
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        name: Upgrade code

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        name: Unused noqa

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format code
        exclude: docs/source-app

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        args: [--line-length=120]
        exclude: docs/source-app

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          #- mdformat-black
          - mdformat_frontmatter
        exclude: |
            (?x)^(
                src/pytorch_lightning/CHANGELOG.md|
                src/lightning_app/CHANGELOG.md|
                src/lightning_lite/CHANGELOG.md
            )$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
